name: Daniel Guay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08908
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c2817'
    - '#84452a'
    - '#a66643'
    - '#c7976d'
    - '#cfa77c'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
