name: Daniel Guay
favicon: null
layout_spectrum: 0.7751043438911438
typography_spectrum: 0.5861865973565727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#83b8e2'
    - '#fefefe'
    - '#010508'
    - '#246794'
    - '#fe95a1'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
